version: '3.8'

services:
  cs2:
    image: joedwards32/cs2:latest
    container_name: cs2-server
    restart: unless-stopped

    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"

    volumes:
      - ./cs2-dedicated:/home/steam/cs2-dedicated
      - ./Steam:/home/steam/Steam
        #- ./entry.sh:/home/steam/entry.sh
    environment:
      - AUTO_UPDATE=false
      - CS2_STARTMAP=de_dust2
      - CS2_LOG_FILE=1
      - CS2_GAMETYPE=0
      - CS2_LAN=1
      - STEAMAPPVALIDATE=0
        # - CS2_IP=0.0.0.0
      - CS2_MAXPLAYERS=10
      - CS2_SERVERNAME=cs2-matin
